apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: tft-analytics-app
build:
  artifacts:
  - image: tzdanows/df
    context: ./data-fetcher
    docker:
      dockerfile: Dockerfile
  tagPolicy: 
    gitCommit: {} 
  local:
    push: true 
deploy:
  kubectl:
    manifests:
    - ./data-fetcher/deployment.yaml
    - ./minio/deployment.yaml
    - ./minio/pv.yaml
    - ./minio/pvc.yaml