# If you have a CI/CD pipeline (like GitHub Actions), 
# you can integrate Skaffold into this pipeline for 
# continuous integration and delivery to your Kubernetes clusters

# currently this skaffold.yaml configuration doesn't work as intended, TODO


apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: tft-analytics-app
build:
  artifacts:
  - image: tzdanows/df
    context: ./data-fetcher
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./data-fetcher/deployment.yaml
