apiVersion: apps/v1
kind: Deployment
metadata:
  name: df
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df
  template:
    metadata:
      labels:
        app: df
    spec:
      containers:
      - name: df
        image: tzdanows/df:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8120
