apiVersion: apps/v1
kind: Deployment
metadata:
  name: df-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: df-test
  template:
    metadata:
      labels:
        app: df-test
    spec:
      containers:
      - name: df-test
        image: tzdanows/df-test:latest
        ports:
        - containerPort: 8080